name: build image and push to dockerhub

on:
  push:
    branches:
      - master
      - deploiement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: stats19/daemon
          tag_with_ref: true
          tags: latest 
          build_args: USERNAME=${{ secrets.API_PROCESS_USERNAME }},PASSWORD=${{ secrets.API_PROCESS_PASSWORD }},SOURCE_BROKER_USERNAME=${{ secrets.RABBIT_USERNAME }},SOURCE_BROKER_PASSWORD=${{ secrets.RABBIT_PASSWORD }},SOURCE_BROKER_QUEUE=${{ secrets.RABBIT_QUEUE }},SOURCE_BROKER_PORT=${{ secrets.RABBIT_PORT }},SOURCE_BROKER_HOST=${{ secrets.RABBIT_HOST }},SOURCE_BROKER_VHOST=${{ secrets.RABBIT_USERNAME }}
